repos:

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest before commit
        entry: uv run pytest test
        language: system
        pass_filenames: false
        always_run: true
