name: Run Tests

on:
  push:
    branches: [main, dev]  # Exécute les tests sur push vers main ou dev
  pull_request:
    branches: [main, dev]  # Exécute les tests sur chaque PR vers main ou dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère ton code source

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Pytest
        run: uv run pytest test